### ISSUE TITLE
Where is options.json?

### ISSUE THREAD

**Issue by ajayyy** [ZLima12/TheEqualizer#1]
Do I make it? Where do I put it. What's the sytax?

Thanks for making this

**Comment by ajayyy** [comment]
Nevermind, it was super simple. I suggest adding it to the readme though, so will leave this issue open
```
{ 
 "auth" : "[code]"
}
```

**Comment by ZLima12** [comment]
I made a table in the Readme that documents all of the different options. This should clear up any confusion.
